--- magma-2.4.0/Makefile	2018-06-25 15:24:56.000000000 -0700
+++ patch-files/Makefile	2018-10-01 18:31:22.707229112 -0700
@@ -72,7 +72,7 @@
     GPU_TARGET += sm_20
 endif
 ifneq ($(findstring Kepler, $(GPU_TARGET)),)
-    GPU_TARGET += sm_30 sm_35
+    GPU_TARGET += sm_30 sm_35 sm_37
 endif
 ifneq ($(findstring Maxwell, $(GPU_TARGET)),)
     GPU_TARGET += sm_50
@@ -116,6 +116,11 @@
     NV_SM    += -gencode arch=compute_35,code=sm_35
     NV_COMP  := -gencode arch=compute_35,code=compute_35
 endif
+ifneq ($(findstring sm37, $(GPU_TARGET)),)
+    MIN_ARCH ?= 370
+    NV_SM    += -gencode arch=compute_37,code=sm_37
+    NV_COMP  := -gencode arch=compute_37,code=compute_37
+endif
 ifneq ($(findstring sm_50, $(GPU_TARGET)),)
     MIN_ARCH ?= 500
     NV_SM    += -gencode arch=compute_50,code=sm_50
