--- magma-2.5.0/Makefile	2019-01-02 11:19:36.000000000 -0800
+++ patch-files/Makefile	2019-03-21 17:34:10.335834998 -0700
@@ -69,11 +69,16 @@
 # NVCC options for the different cards
 # First, add smXX for architecture names
 ifneq ($(findstring Kepler, $(GPU_TARGET)),)
-    GPU_TARGET += sm_30 sm_35
+    GPU_TARGET += sm_35 sm_37
 endif
 ifneq ($(findstring Maxwell, $(GPU_TARGET)),)
     GPU_TARGET += sm_50
 endif
+ifneq ($(findstring sm37, $(GPU_TARGET)),)
+    MIN_ARCH ?= 370
+    NV_SM    += -gencode arch=compute_37,code=sm_37
+    NV_COMP  := -gencode arch=compute_37,code=compute_37
+endif
 ifneq ($(findstring Pascal, $(GPU_TARGET)),)
     GPU_TARGET += sm_60
 endif
